<h1>Eliminação de Gauss com Python</h1>
<table>
  <tr>
    <td><b>Aluno:</b></td><td>Gabriel A. Rocha (ragproggramer)</td>
  </tr>
  <tr>
    <td><b>Turma:</b></td><td>3º Semestre Eng. Eletrica</td>
  </tr>
  <tr>
    <td><b>Professor:</b></td><td>Leonardo</td>
  </tr>
  <tr>
    <td><b>Data de Hoje:</b></td><td>20/06/2025</td>
  </tr>
  <tr>
    <td><b>Data de Entrega:</b></td><td>20/06/2025</td>
  </tr>
</table>
<hr>
<p>Este notebook apresenta o passo a passo para resolver sistemas lineares usando o método da eliminação de Gauss.</p>


<h2>🎯 Objetivo</h2>
<p>Neste trabalho, implementaremos passo a passo o método da eliminação de Gauss com pivoteamento parcial para resolver sistemas lineares.

## 🧮 Sistema a ser resolvido proposto pelo professor

Vamos resolver o seguinte sistema:
\begin{cases}
-1x_1 - 1x_2 + 2x_3 - 1x_4 = -8 \\
+1x_1 + 1x_2 + 0x_3 + 0x_4 = 1 \\
+1x_1 + 1x_2 + 1x_3 - 1x_4 = -6 \\
-2x_1 + 3x_2 + 2x_3 - 2x_4 = -2 \\
\end{cases}



In [2]:
import numpy as np # Importando a biblioteca NumPy

# Matriz A (coeficientes) 
A = np.array([
    [-1, -1, 2, -1], 
    [1, 1, 0, 0], 
    [1, 1, 1, -1],
    [-2, 3, 2, -2]
])
# Vetor b (igualdade)
b = np.array([[-8], [1], [-6], [-2]])

<h2>📌 Etapa 1: Construção da Matriz Aumentada</h2>
<p>Vamos unir a matriz de coeficientes <code>A</code> com o vetor de termos independentes <code>b</code>, formando a matriz aumentada <code>[A | b]</code>.</p>


In [3]:
def matriz_aumentada(A, b):
    return np.column_stack((A, b)).astype(float)

Ab = matriz_aumentada(A, b)
print("Matriz aumentada [A | b]:\n", Ab)

Matriz aumentada [A | b]:
 [[-1. -1.  2. -1. -8.]
 [ 1.  1.  0.  0.  1.]
 [ 1.  1.  1. -1. -6.]
 [-2.  3.  2. -2. -2.]]


<h2>🔧 Etapa 2: Eliminação de Gauss com Pivoteamento</h2>
<p>Nesta etapa, aplicamos o escalonamento com <strong>pivoteamento parcial</strong>, ou seja, trocamos as linhas para garantir que o maior elemento (em módulo) da coluna pivô esteja na diagonal. Isso evita divisões por números muito pequenos e melhora a estabilidade numérica.</p>


In [4]:
def eliminacao_pivoteamento(A):
    N = len(A)
    for i in range(N):
        # Pivoteamento parcial (troca de linhas)
        max_index = i + np.argmax(np.abs(A[i:, i]))
        if max_index != i:
            A[[i, max_index]] = A[[max_index, i]]

        # Escalonamento
        for j in range(i + 1, N):
            fator = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - fator * A[i, i:]
            A[j, i] = 0.0  # Correção para evitar lixo numérico
    return A


<h2>🔄 Etapa 3: Substituição Regressiva</h2>
<p>Com a matriz em forma triangular superior, utilizamos substituição de trás para frente para encontrar os valores de <code>x</code>.</p>
<pre>
x_n = b_n / a_nn
x_{n-1} = (b_{n-1} - a_{n-1,n}x_n) / a_{n-1,n-1}
...
</pre>


In [5]:
def substituicao_regressiva(A):
    N = len(A)
    for i in range(N - 1, -1, -1):
        for j in range(N - 1, i, -1):
            A[i, -1] -= A[i, j] * A[j, -1]
        A[i, -1] /= A[i, i]
    return A[:, -1]


<h2>✅ Etapa Final: Solução do Sistema</h2>
<p>Agora unimos todas as etapas em uma função que resolve o sistema linear completo.</p>


In [8]:
def gauss(A, b):
    Ab = matriz_aumentada(A, b)
    Ab = eliminacao_pivoteamento(Ab)
    x = substituicao_regressiva(Ab)
    return x

# Executando o método de eliminação de Gauss
x = gauss(A, b)

print("Solução do sistema: \n", x)
if np.all(np.isfinite(x)):
    print("O método convergiu para uma solução.")
else:
    print("O método não convergiu.")


Solução do sistema: 
 [-1.8  2.8  0.   7. ]
O método convergiu para uma solução.


<h2>📝 Conclusão</h2>
<p>Com este notebook, implementamos a eliminação de Gauss com pivoteamento parcial para resolver sistemas lineares. A técnica garante mais estabilidade numérica e evita erros em casos com divisores pequenos.</p>
